language: python
python:
  - "2.7"
# command to install dependencies
cache:
  directories:
    - $HOME/.cache/pip#before_install
install:
  - pip install -r requirements.txt
  - sudo mv nltk_data /usr/share/nltk_data
# command to run tests
script:
  - sudo python setup.py test
notifications:
  email: false
